#pragma once

#include "training_stats.h"
#include "qtable.h"

#include <array>
#include <cstdint>
#include <random>
#include <string>
#include <vector>
#include <filesystem>

class Trainer {
public:
    struct Options {
        uint32_t episodes = 1;
        uint32_t seed = 1337;

        float alpha = 0.15f;
        float gamma = 0.90f;
        float epsilon = 1.0f;
        float epsilonDecay = 0.95f;
        float epsilonMin = 0.02f;

        uint16_t sampleRate = 16384;
        bool usePcmState = true;

        bool reset = true;
        std::string modelPath = "model.qtbl";

        // Memory-optimized dataset cycling.
        // One episode trains only this many files at once.
        // Across the full run, all files are scheduled equally often
        // or with a maximum deviation of one slot if the math has a remainder.
        uint32_t workingSetSize = 4;

        // Store FFmpeg-produced f32le PCM files on disk next to the dataset
        // in .pcmcache, instead of keeping every decoded WAV in RAM.
        bool usePcmCache = true;

        // During a run, PCM cache files are always kept while needed.
        // If false, cache files created by this run are deleted at the end.
        bool keepPcmCache = true;

        // Two-phase training.
        // Phase 1: Teacher forcing, prevByte = previous teacher byte.
        // Phase 2: Student forcing, prevByte = previous student/generated byte.
        bool useStudentForcing = true;

        // Share of the run used for teacher forcing before switching.
        // The actual switch episode is rounded down to a fair scheduler boundary.
        float teacherForcingRatio = 0.70f;

        // When student forcing starts, epsilon is raised to at least this value
        // so the model can explore its own generated paths.
        float studentForcingEpsilon = 0.25f;
        bool boostEpsilonOnStudentSwitch = true;
    };

    struct Result {
        bool ok = false;
        std::string error;
        uint64_t filesLoaded = 0;
        TrainingStats stats;
    };

    Result trainRandomBaseline(
        const std::string& datasetFolder,
        const Options& options = Options{}
    );

    Result trainQTable(
        const std::string& datasetFolder,
        const Options& options = Options{}
    );

private:
    struct DatasetEntry {
        std::filesystem::path qltcPath;
        std::filesystem::path wavPath;
    };

    struct TrainingItem {
        std::vector<uint8_t> teacherPayload;
        std::vector<float> pcmInterleaved;
        uint32_t frames = 0;
        std::string name;
    };

    std::vector<uint8_t> validSymbols;
    std::mt19937 rng;

    size_t chooseAction(QTable& table, uint32_t state, float epsilon);

    bool scanTrainingDataset(
        const std::string& datasetFolder,
        std::vector<DatasetEntry>& entries,
        std::string& error
    );

    std::vector<std::vector<size_t>> buildBalancedSchedule(
        size_t fileCount,
        uint32_t workingSetSize,
        uint32_t episodes
    );

    uint32_t computeStudentSwitchEpisode(
        size_t fileCount,
        uint32_t workingSetSize,
        uint32_t episodes,
        float teacherRatio
    ) const;

    bool loadTrainingItem(
        const DatasetEntry& entry,
        const Options& options,
        TrainingItem& item,
        std::vector<std::filesystem::path>& createdPcmCaches,
        std::string& error
    );

    void trainItem(
        const TrainingItem& item,
        QTable& table,
        float epsilon,
        const Options& options,
        bool studentForcing,
        TrainingStats& stats,
        std::array<uint64_t, 7>* episodeTopfCounts,
        std::array<uint64_t, 7>* runTopfCounts
    );

    std::filesystem::path makePcmCachePath(
        const std::filesystem::path& qltcPath,
        uint16_t sampleRate
    ) const;

    bool preprocessWavToF32Stereo(
        const std::string& wavPath,
        const std::string& pcmPath,
        uint16_t sampleRate,
        std::string& error
    );

    bool loadF32StereoPcm(
        const std::string& pcmPath,
        std::vector<float>& interleaved,
        uint32_t& frames,
        std::string& error
    );

    bool loadDatasetPayloads(
        const std::string& datasetFolder,
        std::vector<std::vector<uint8_t>>& payloads,
        std::string& error
    );

    uint8_t randomValidByte();
};
